name: default

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install terraform
        uses: hashicorp/setup-terraform@v1
      - run: make lint

  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: [ lint ]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install terraform
        uses: hashicorp/setup-terraform@v1
      - run: make tests
